rateLimitRules:
  - /v1/test:
      interval: 60
      capacity: 2
      quantum: 2
  - /v1/ping:
      interval: 1
      capacity: 1
      quantum: 2

fuseRules:
  - test1:
      timeout: 1000
      maxConcurrentRequests: 1000
      sleepWindow: 6000
      requestVolumeThreshold: 1000
      errorPercentThreshold: 50

i18n:
  defaultLanguage: "zh"