cors:
  enable: true

errorCache:
  enable: true

logging:
  requestLogEnable: true

rateLimitRules:
  - /v1/test:
      interval: 60
      capacity: 10
      quantum: 10
  - /v1/lang:
      interval: 60
      capacity: 2
      quantum: 2
fuse:
  enable: true
  fuseRules:
    - test1:
        timeout: 1000
        maxConcurrentRequests: 1000
        sleepWindow: 6000
        requestVolumeThreshold: 5
        errorPercentThreshold: 50

i18n:
  enable: true
  defaultLanguage: "zh"

myName: "txllain"
myAge: 18
ex:
  exName: "exhoy"

logAccess:
  filePath:

logError:
  filePath: